theme: jekyll-theme-modernist
title: Java.PS
description: Java by Petr Sladek
url: https://www.java.ps/
base: https://www.java.ps/
show_downloads: "false"
author: Petr Sladek
exclude: [ '*.yml', 'CNAME' ]